/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.9.1.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as addCard from "../addCard";
import type * as addCardToDeck from "../addCardToDeck";
import type * as addDeck from "../addDeck";
import type * as deckStats from "../deckStats";
import type * as getDeck from "../getDeck";
import type * as listCards from "../listCards";
import type * as listDecks from "../listDecks";
import type * as listMessages from "../listMessages";
import type * as removeCardFromDeck from "../removeCardFromDeck";
import type * as reviewCard from "../reviewCard";
import type * as sendMessage from "../sendMessage";
import type * as showNextCard from "../showNextCard";
import type * as storeUser from "../storeUser";
import type * as updateCard from "../updateCard";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  addCard: typeof addCard;
  addCardToDeck: typeof addCardToDeck;
  addDeck: typeof addDeck;
  deckStats: typeof deckStats;
  getDeck: typeof getDeck;
  listCards: typeof listCards;
  listDecks: typeof listDecks;
  listMessages: typeof listMessages;
  removeCardFromDeck: typeof removeCardFromDeck;
  reviewCard: typeof reviewCard;
  sendMessage: typeof sendMessage;
  showNextCard: typeof showNextCard;
  storeUser: typeof storeUser;
  updateCard: typeof updateCard;
}>;
